### ISSUE TITLE
OSError: exception: privileged instruction

### ISSUE THREAD

**Issue by mrtmy1** [starofrainnight/rabird.winio#19]
* pywinio version: 
* Python version: python 3.4 and python 2.7
* Operating System: windows xp x86

### Description

hello i am trying to send keys for windows xp.  1 2 minutes the program runs without error.  then it gives an error (OSError: exception: privileged instruction). how do i solve this problem. I would be glad if you help.

I read Privilege Requirements in Readme.rst.

"Using WinIo from a service running as LocalSystem (SE_LOAD_DRIVER_NAME privilege must be explicitly enabled)."

I did not understand how to do this.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by starofrainnight** [comment]
If you don't understand, then you have better not go through the way : "Using WinIo from a service running as LocalSystem" .

You could just run your script under a console environment (cmd.exe) with "Administrator" permission.

But the real problem is, if you have "1 2 minutes the program runs without error“, why it can't later.

**Comment by starofrainnight** [comment]
Long time no response, close this issue.
