### ISSUE TITLE
does it work for usb keyboard?

### ISSUE THREAD

**Issue by limu0317** [starofrainnight/rabird.winio#2]
I complement a similar one in python, but it doesn't work.
It is said that winio lib only work with PS/2 interface keyboard, is it right?

**Comment by starofrainnight** [comment]
Yep, it only work while you have a PS/2 keyboard or mouse, otherwise you will see the blue screen or lucky with nothing happen.

I also trying to find another way to instead the keyboard/mouse software control in my PC automation library : rabird.auto , maybe implement a custom virtual USB keyboard/mouse driver is a better choice.
