### ISSUE TITLE
how to use rabird.winio

### ISSUE THREAD

**Issue by respark** [starofrainnight/rabird.winio#3]
can u make a sample code tell us how to use rabird.winio? thanks.

**Comment by starofrainnight** [comment]
```
Surprising! I don't expect have
  someone will use this library except me. I will commit some sample
  code at this end of week.


-------- Original Message --------
  Title: [rabird.winio] how to use rabird.winio (#3)
  From: notifications@github.com
  To: rabird.winio@noreply.github.com; Cc: 
  Date:  2016/03/06 22:41:06



  can u make a sample code tell us how to use rabird.winio?
    thanks.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by respark** [comment]
thanks a lot,i sitting on thorn waitting for u

**Comment by starofrainnight** [comment]
I added a simple sample at "Usage" section in README.rst. 

This library have not yet complete supported all standard WinIO library abilities.

Only get_port__() and set_port__() be supported, other function just like GetPhysLong(), SetPhysLong(),  MapPhysToLin() and UnmapPhysicalMemory() are unsupported.

Because this library just wrote for my personal requirement, I don't know when I have time to finish them all.
